#!/bin/bash

set -e

verbose=0

git_cmd() {
    if [ "$verbose" -eq 1 ]; then
        echo "+ git $*" >&2
    fi
    git "$@"
}

project=$(basename "$PWD")

case "${1:-}" in
    -v)
        verbose=1
        shift
        ;;
esac

case "${1:-}" in
    -d|-D)
        delete_flag="$1"
        shift
        case "${1:-}" in
            ''|*[!0-9]*)
                echo "Usage: doop $delete_flag <issue-number>" >&2
                exit 1
                ;;
        esac
        issue="$1"
        remote="${project}-${issue}"
        remote_and_branch=$(git_cmd branch -r | grep -E "${issue}.+${issue}")
        branch="${remote_and_branch#*/}"
        git_cmd branch "$delete_flag" "$branch"
        git_cmd remote remove "$remote"
        ;;
    ''|*[!0-9]*)
        echo "Usage: doop <issue-number>" >&2
        exit 1
        ;;
    *)
        issue="$1"
        remote="${project}-${issue}"
        if ! git_cmd remote get-url "$remote" &>/dev/null; then
            git_cmd remote add "$remote" "git@git.drupal.org:issue/${remote}.git"
        fi
        git_cmd fetch "$remote"
        remote_and_branch=$(git_cmd branch -r | grep -E "${issue}.+${issue}")
        branch="${remote_and_branch#*/}"
        git_cmd fetch "$remote" "$branch":"$branch"
        ;;
esac
